--
-- Test GIN indexes.
--
-- There are other tests to test different GIN opclassed. This is for testing
-- GIN itself.
-- Create and populate a test table with a GIN index.
create table gin_test_tbl(i int4[]);
CREATE TABLE
create index gin_test_idx on gin_test_tbl using gin (i) with (fastupdate = on);
CREATE INDEX
insert into gin_test_tbl select array[1, 2, g] from generate_series(1, 20000) g;
INSERT 0 20000
insert into gin_test_tbl select array[1, 3, g] from generate_series(1, 1000) g;
INSERT 0 1000
vacuum gin_test_tbl; -- flush the fastupdate buffers
VACUUM
-- Test vacuuming
delete from gin_test_tbl where i @> array[2];
DELETE 20001
vacuum gin_test_tbl;
VACUUM
-- Disable fastupdate, and do more insertions. With fastupdate enabled, most
-- insertions (by flushing the list pages) cause page splits. Without
-- fastupdate, we get more churn in the GIN data leaf pages, and exercise the
-- recompression codepaths.
alter index gin_test_idx set (fastupdate = off);
ALTER INDEX
insert into gin_test_tbl select array[1, 2, g] from generate_series(1, 1000) g;
INSERT 0 1000
insert into gin_test_tbl select array[1, 3, g] from generate_series(1, 1000) g;
INSERT 0 1000
delete from gin_test_tbl where i @> array[2];
DELETE 1001
vacuum gin_test_tbl;
VACUUM
