--
-- Test for facilities of security label
--
-- initial setups
SET client_min_messages TO 'warning';
SET
DROP ROLE IF EXISTS seclabel_user1;
DROP ROLE
DROP ROLE IF EXISTS seclabel_user2;
DROP ROLE
DROP TABLE IF EXISTS seclabel_tbl1;
DROP TABLE
DROP TABLE IF EXISTS seclabel_tbl2;
DROP TABLE
DROP TABLE IF EXISTS seclabel_tbl3;
DROP TABLE
CREATE USER seclabel_user1 WITH CREATEROLE;
CREATE ROLE
CREATE USER seclabel_user2;
CREATE ROLE
CREATE TABLE seclabel_tbl1 (a int, b text);
CREATE TABLE
CREATE TABLE seclabel_tbl2 (x int, y text);
CREATE TABLE
CREATE VIEW seclabel_view1 AS SELECT * FROM seclabel_tbl2;
CREATE VIEW
CREATE FUNCTION seclabel_four() RETURNS integer AS $$SELECT 4$$ language sql;
CREATE FUNCTION
CREATE DOMAIN seclabel_domain AS text;
CREATE DOMAIN
ALTER TABLE seclabel_tbl1 OWNER TO seclabel_user1;
ALTER TABLE
ALTER TABLE seclabel_tbl2 OWNER TO seclabel_user2;
ALTER TABLE
RESET client_min_messages;
RESET
--
-- Test of SECURITY LABEL statement without a plugin
--
SECURITY LABEL ON TABLE seclabel_tbl1 IS 'classified';			-- fail
ERROR:  22023: no security label providers have been loaded
SECURITY LABEL FOR 'dummy' ON TABLE seclabel_tbl1 IS 'classified';		-- fail
ERROR:  22023: security label provider "dummy" is not loaded
SECURITY LABEL ON TABLE seclabel_tbl1 IS '...invalid label...';		-- fail
ERROR:  22023: no security label providers have been loaded
SECURITY LABEL ON TABLE seclabel_tbl3 IS 'unclassified';			-- fail
ERROR:  22023: no security label providers have been loaded
SECURITY LABEL ON ROLE seclabel_user1 IS 'classified';			-- fail
ERROR:  22023: no security label providers have been loaded
SECURITY LABEL FOR 'dummy' ON ROLE seclabel_user1 IS 'classified';		-- fail
ERROR:  22023: security label provider "dummy" is not loaded
SECURITY LABEL ON ROLE seclabel_user1 IS '...invalid label...';		-- fail
ERROR:  22023: no security label providers have been loaded
SECURITY LABEL ON ROLE seclabel_user3 IS 'unclassified';			-- fail
ERROR:  22023: no security label providers have been loaded
-- clean up objects
DROP FUNCTION seclabel_four();
DROP FUNCTION
DROP DOMAIN seclabel_domain;
DROP DOMAIN
DROP VIEW seclabel_view1;
DROP VIEW
DROP TABLE seclabel_tbl1;
DROP TABLE
DROP TABLE seclabel_tbl2;
DROP TABLE
DROP USER seclabel_user1;
DROP ROLE
DROP USER seclabel_user2;
DROP ROLE
