--
-- VACUUM
--
CREATE TABLE vactst (i INT);
CREATE TABLE
INSERT INTO vactst VALUES (1);
INSERT 0 1
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 1
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 2
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 4
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 8
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 16
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 32
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 64
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 128
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 256
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 512
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 1024
INSERT INTO vactst VALUES (0);
INSERT 0 1
SELECT count(*) FROM vactst;
 count 
-------
  2049
(1 row)

DELETE FROM vactst WHERE i != 0;
DELETE 2048
SELECT * FROM vactst;
 i 
---
 0
(1 row)

VACUUM FULL vactst;
VACUUM
UPDATE vactst SET i = i + 1;
UPDATE 1
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 1
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 2
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 4
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 8
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 16
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 32
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 64
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 128
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 256
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 512
INSERT INTO vactst SELECT * FROM vactst;
INSERT 0 1024
INSERT INTO vactst VALUES (0);
INSERT 0 1
SELECT count(*) FROM vactst;
 count 
-------
  2049
(1 row)

DELETE FROM vactst WHERE i != 0;
DELETE 2048
VACUUM (FULL) vactst;
VACUUM
DELETE FROM vactst;
DELETE 1
SELECT * FROM vactst;
 i 
---
(0 rows)

VACUUM (FULL, FREEZE) vactst;
VACUUM
VACUUM (ANALYZE, FULL) vactst;
VACUUM
CREATE TABLE vaccluster (i INT PRIMARY KEY);
CREATE TABLE
ALTER TABLE vaccluster CLUSTER ON vaccluster_pkey;
ALTER TABLE
CLUSTER vaccluster;
CLUSTER
CREATE FUNCTION do_analyze() RETURNS VOID VOLATILE LANGUAGE SQL
	AS 'ANALYZE pg_am';
CREATE FUNCTION
CREATE FUNCTION wrap_do_analyze(c INT) RETURNS INT IMMUTABLE LANGUAGE SQL
	AS 'SELECT $1 FROM do_analyze()';
CREATE FUNCTION
CREATE INDEX ON vaccluster(wrap_do_analyze(i));
CREATE INDEX
INSERT INTO vaccluster VALUES (1), (2);
INSERT 0 2
ANALYZE vaccluster;
ERROR:  0A000: ANALYZE cannot be executed from VACUUM or ANALYZE
CONTEXT:  SQL function "do_analyze" statement 1
SQL function "wrap_do_analyze" statement 1
VACUUM FULL pg_am;
VACUUM
VACUUM FULL pg_class;
VACUUM
VACUUM FULL pg_database;
VACUUM
VACUUM FULL vaccluster;
ERROR:  0A000: ANALYZE cannot be executed from VACUUM or ANALYZE
CONTEXT:  SQL function "do_analyze" statement 1
SQL function "wrap_do_analyze" statement 1
VACUUM FULL vactst;
VACUUM
-- check behavior with duplicate column mentions
VACUUM ANALYZE vaccluster(i,i);
ERROR:  42701: column "i" of relation "vaccluster" appears more than once
ANALYZE vaccluster(i,i);
ERROR:  42701: column "i" of relation "vaccluster" appears more than once
DROP TABLE vaccluster;
DROP TABLE
DROP TABLE vactst;
DROP TABLE
