--
-- PREPARED TRANSACTIONS (two-phase commit)
--
-- We can't readily test persistence of prepared xacts within the
-- regression script framework, unfortunately.  Note that a crash
-- isn't really needed ... stopping and starting the postmaster would
-- be enough, but we can't even do that here.
-- create a simple table that we'll use in the tests
CREATE TABLE pxtest1 (foobar VARCHAR(10));
CREATE TABLE
INSERT INTO pxtest1 VALUES ('aaa');
INSERT 0 1
-- Test PREPARE TRANSACTION
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
UPDATE pxtest1 SET foobar = 'bbb' WHERE foobar = 'aaa';
UPDATE 1
SELECT * FROM pxtest1;
 foobar 
--------
 bbb
(1 row)

PREPARE TRANSACTION 'foo1';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

-- Test pg_prepared_xacts system view
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- Test ROLLBACK PREPARED
ROLLBACK PREPARED 'foo1';
ERROR:  42704: prepared transaction with identifier "foo1" does not exist
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- Test COMMIT PREPARED
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
INSERT INTO pxtest1 VALUES ('ddd');
INSERT 0 1
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
 ddd
(2 rows)

PREPARE TRANSACTION 'foo2';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

COMMIT PREPARED 'foo2';
ERROR:  42704: prepared transaction with identifier "foo2" does not exist
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

-- Test duplicate gids
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
UPDATE pxtest1 SET foobar = 'eee' WHERE foobar = 'ddd';
UPDATE 0
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

PREPARE TRANSACTION 'foo3';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
INSERT INTO pxtest1 VALUES ('fff');
INSERT 0 1
-- This should fail, because the gid foo3 is already in use
PREPARE TRANSACTION 'foo3';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

ROLLBACK PREPARED 'foo3';
ERROR:  42704: prepared transaction with identifier "foo3" does not exist
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

-- Test serialization failure (SSI)
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
UPDATE pxtest1 SET foobar = 'eee' WHERE foobar = 'ddd';
UPDATE 0
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

PREPARE TRANSACTION 'foo4';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
SELECT * FROM pxtest1;
 foobar 
--------
 aaa
(1 row)

-- This should fail, because the two transactions have a write-skew anomaly
INSERT INTO pxtest1 VALUES ('fff');
INSERT 0 1
PREPARE TRANSACTION 'foo5';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

ROLLBACK PREPARED 'foo4';
ERROR:  42704: prepared transaction with identifier "foo4" does not exist
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- Clean up
DROP TABLE pxtest1;
DROP TABLE
-- Test subtransactions
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
  CREATE TABLE pxtest2 (a int);
CREATE TABLE
  INSERT INTO pxtest2 VALUES (1);
INSERT 0 1
  SAVEPOINT a;
SAVEPOINT
    INSERT INTO pxtest2 VALUES (2);
INSERT 0 1
  ROLLBACK TO a;
ROLLBACK
  SAVEPOINT b;
SAVEPOINT
  INSERT INTO pxtest2 VALUES (3);
INSERT 0 1
PREPARE TRANSACTION 'regress-one';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
CREATE TABLE pxtest3(fff int);
CREATE TABLE
-- Test shared invalidation
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
  DROP TABLE pxtest3;
DROP TABLE
  CREATE TABLE pxtest4 (a int);
CREATE TABLE
  INSERT INTO pxtest4 VALUES (1);
INSERT 0 1
  INSERT INTO pxtest4 VALUES (2);
INSERT 0 1
  DECLARE foo CURSOR FOR SELECT * FROM pxtest4;
DECLARE CURSOR
  -- Fetch 1 tuple, keeping the cursor open
  FETCH 1 FROM foo;
 a 
---
 1
(1 row)

PREPARE TRANSACTION 'regress-two';
ERROR:  55000: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
-- No such cursor
FETCH 1 FROM foo;
ERROR:  34000: cursor "foo" does not exist
-- Table doesn't exist, the creation hasn't been committed yet
SELECT * FROM pxtest2;
ERROR:  42P01: relation "pxtest2" does not exist
LINE 1: SELECT * FROM pxtest2;
                      ^
-- There should be two prepared transactions
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- pxtest3 should be locked because of the pending DROP
begin;
BEGIN
lock table pxtest3 in access share mode nowait;
LOCK TABLE
rollback;
ROLLBACK
-- Disconnect, we will continue testing in a different backend
\c -
You are now connected to database "highgo" as user "highgo".
-- There should still be two prepared transactions
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- pxtest3 should still be locked because of the pending DROP
begin;
BEGIN
lock table pxtest3 in access share mode nowait;
LOCK TABLE
rollback;
ROLLBACK
-- Commit table creation
COMMIT PREPARED 'regress-one';
ERROR:  42704: prepared transaction with identifier "regress-one" does not exist
\d pxtest2
psql:/home/postgres/build_out/sql/prepared_xacts.sql:142: Did not find any relation named "pxtest2".
SELECT * FROM pxtest2;
ERROR:  42P01: relation "pxtest2" does not exist
LINE 1: SELECT * FROM pxtest2;
                      ^
-- There should be one prepared transaction
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- Commit table drop
COMMIT PREPARED 'regress-two';
ERROR:  42704: prepared transaction with identifier "regress-two" does not exist
SELECT * FROM pxtest3;
 fff 
-----
(0 rows)

-- There should be no prepared transactions
SELECT gid FROM pg_prepared_xacts;
 gid 
-----
(0 rows)

-- Clean up
DROP TABLE pxtest2;
ERROR:  42P01: table "pxtest2" does not exist
DROP TABLE pxtest3;  -- will still be there if prepared xacts are disabled
DROP TABLE
DROP TABLE pxtest4;
ERROR:  42P01: table "pxtest4" does not exist
